version: '3.8'

services:
  aiConfig1:
    container_name: aiConfig1
    image: mongo:latest
    command: mongod --configsvr --replSet repConfAiBulb --port 27017 --dbpath /data/configdb
    volumes:
      - aiconfig1:/data/configdb
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.5
    deploy:
      replicas: 1
    restart: unless-stopped

  aiConfig2:
    image: mongo:latest
    container_name: aiConfig2
    command: mongod --configsvr --replSet repConfAiBulb --port 27017 --dbpath /data/configdb
    volumes:
      - aiconfig2:/data/configdb
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.6
    deploy:
      replicas: 1
    restart: unless-stopped

  aiRouter1:      # 10.10.0.2
    image: mongo:latest
    container_name: aiRouter1
    command: mongos --port 27017 --configdb repConfAiBulb/10.10.0.5:27017,10.10.0.6:27017 --bind_ip_all
    ports:
      - 27017:27017
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.2

  aiRouter2:      # 10.10.0.3
    image: mongo:latest
    container_name: aiRouter2
    command: mongos --port 27017 --configdb repConfAiBulb/10.10.0.5:27017,10.10.0.6:27017 --bind_ip_all
    ports:
      - "27018:27017"
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.3
    
  aiRouter3:    # 10.10.0.4
    image: mongo:latest
    container_name: aiRouter3
    command: mongos --port 27017 --configdb repConfAiBulb/10.10.0.5:27017,10.10.0.6:27017 --bind_ip_all
    ports:
      - "27019:27017"
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.4

  eastCoast:     # 10.10.0.7
    image: mongo:latest
    container_name: eastCoast
    command: mongod --port 27017 --shardsvr --replSet repUSA --dbpath /data/db --bind_ip_all 
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.7
    volumes:
      - eastCoast:/data/db

  westCoast:     # 10.10.0.8
    image: mongo:latest
    container_name: westCoast
    command: mongod --port 27017 --shardsvr --replSet repUSA --dbpath /data/db --bind_ip_all
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.8
    volumes:
      - westCoast:/data/db

  norte:      # 10.10.0.9
    image: mongo:latest
    container_name: norte
    command: mongod --port 27017 --shardsvr --replSet repMex --bind_ip_all
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.9
    volumes:
      - norte:/data/db

  centroSur:  # 10.10.0.10
    image: mongo:latest
    container_name: centroSur
    command: mongod --port 27017 --shardsvr --replSet repMex --bind_ip_all
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.10
    volumes:
      - centroSur:/data/db

  sanJose:     # 10.10.0.11
    image: mongo:latest
    container_name: sanJose
    command: mongod --port 27017 --shardsvr --replSet repCR --bind_ip_all
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.11
    volumes:
      - sanJose:/data/db

  limon:      # 10.10.0.12
    image: mongo:latest
    container_name: limon
    command: mongod --port 27017 --shardsvr --replSet repCR --bind_ip_all
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.12
    volumes:
      - limon:/data/db

  guate:       # 10.10.0.13
    image: mongo:latest
    container_name: guate
    command: mongod --port 27017 --shardsvr --replSet repGuate --bind_ip_all
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.13
    volumes:
      - guate:/data/db
    
  xela:       # 10.10.0.14
    image: mongo:latest
    container_name: xela
    command: mongod --port 27017 --shardsvr --replSet repGuate --bind_ip_all
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.14
    volumes:
      - xela:/data/db

  usa-arb:     # 10.10.0.15
    image: mongo:latest
    container_name: usa-arb
    command: mongod --port 27017 --dbpath /data/db --replSet repUSA
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.15
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.replica == usa
    volumes:
      - usa-arb:/data/db

  mex-arb:     # 10.10.0.16
    image: mongo:latest
    container_name: mex-arb
    command: mongod --port 27017 --dbpath /data/db --replSet repMex
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.16
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.replica == mex
    volumes:
      - mex-arb:/data/db

  cr-arb:      # 10.10.0.17
    image: mongo:latest
    container_name: cr-arb
    command: mongod --port 27017 --dbpath /data/db --replSet repCR
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.17
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.replica == costa_rica
    volumes:
      - cr-arb:/data/db

  guate-arb:  # 10.10.0.18
    image: mongo:latest
    container_name: guate-arb
    command: mongod --port 27017 --dbpath /data/db --replSet repGuate
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.18
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.replica == guatemala
    volumes:
      - guate-arb:/data/db

volumes:
  aiconfig1:
  aiconfig2:
  eastCoast:
  westCoast:
  norte:
  centroSur:
  sanJose:
  limon:
  guate:
  xela:
  usa-arb:
  mex-arb:
  cr-arb:
  guate-arb:
  
networks:
  mongo-vpn:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/16