version: '3.8'

services:
  aiConfig1:
    container_name: aiConfig1
    image: mongo:latest
    command: mongod --configsvr --replSet repConfAiBulb --port 27017 --dbpath /data/configdb --bind_ip_all
    ports:
      - 27017:27017
    volumes:
      - aiconfig1:/data/configdb
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.5
    deploy:
      replicas: 1
    restart: unless-stopped

  eastCoast:
    image: mongo:latest
    container_name: eastCoast
    command: mongod --port 27017 --shardsvr --replSet repUSA --dbpath /data/db --bind_ip_all
    ports:
      - 27019:27017
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.7
    volumes:
      - eastCoast:/data/db

  norte:
    image: mongo:latest
    container_name: norte
    command: mongod --port 27017 --shardsvr --replSet repMex --bind_ip_all
    ports:
      - 27020:27017
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.9
    volumes:
      - norte:/data/db

  aiRouter1:      # 10.10.0.2
    image: mongo:latest
    container_name: aiRouter1
    command: mongos --port 27017 --configdb repConfAiBulb/10.10.0.5:27017,10.10.0.6:27017 --bind_ip_all
    ports:
      - "27027:27017"
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.2

  aiRouter2:      # 10.10.0.3
    image: mongo:latest
    container_name: aiRouter2
    command: mongos --port 27017 --configdb repConfAiBulb/10.10.0.5:27017,10.10.0.6:27017 --bind_ip_all
    ports:
      - "27028:27017"
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.3
    
  aiRouter3:    # 10.10.0.4
    image: mongo:latest
    container_name: aiRouter3
    command: mongos --port 27017 --configdb repConfAiBulb/10.10.0.5:27017,10.10.0.6:27017 --bind_ip_all
    ports:
      - "27029:27017"
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.4

volumes:
  aiconfig1:
  eastCoast:
  norte:

networks:
  mongo-vpn:
    name: mongo-vpn 
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/16
