version: '3.8'

services:
  sanJose:     # 10.10.0.11
    image: mongo:latest
    container_name: sanJose
    command: mongod --port 27017 --shardsvr --replSet repCR --bind_ip_all
    ports:
      - 27023:27017
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.11
    volumes:
      - sanJose:/data/db

  guate:       # 10.10.0.13
    image: mongo:latest
    container_name: guate
    command: mongod --port 27017 --shardsvr --replSet repGuate --bind_ip_all
    ports:
      - 27024:27017
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.13
    volumes:
      - guate:/data/db

  guate-arb:  # 10.10.0.18
    image: mongo:latest
    container_name: guate-arb
    command: mongod --port 27017 --dbpath /data/db --replSet repGuate
    ports:
      - 27031:27017
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.18
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.replica == guatemala
    volumes:
      - guate-arb:/data/db

volumes:
  sanJose:
  guate:
  guate-arb:

networks:
  mongo-vpn:
    name: mongo-vpn 
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/16