version: '3.8'

services:
  westCoast:     # 10.10.0.8
    image: mongo:latest
    container_name: westCoast
    command: mongod --port 27017 --shardsvr --replSet repUSA --dbpath /data/db --bind_ip_all
    ports:
      - 27021:27017
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.8
    volumes:
      - westCoast:/data/db

  centroSur:  # 10.10.0.10
    image: mongo:latest
    container_name: centroSur
    command: mongod --port 27017 --shardsvr --replSet repMex --bind_ip_all
    ports:
      - 27022:27017
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.10
    volumes:
      - centroSur:/data/db

  usa-arb:     # 10.10.0.15
    image: mongo:latest
    container_name: usa-arb
    command: mongod --port 27017 --dbpath /data/db --replSet repUSA
    ports:
      - 27030:27017
    networks:
      mongo-vpn:
        ipv4_address: 10.10.0.15
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.replica == usa
    volumes:
      - usa-arb:/data/db

volumes:
  westCoast:
  centroSur:
  usa-arb:

networks:
  mongo-vpn:
    name: mongo-vpn 
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/16